# Generated by Django 6.0.1 on 2026-02-08 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.TextField()),
                ('token', models.TextField()),
                ('server_id', models.CharField(max_length=16)),
                ('lang', models.CharField(default='ru-ru', max_length=32)),
                ('status', models.CharField(default='new', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(db_index=True, max_length=64)),
                ('pool_name', models.CharField(blank=True, default='', max_length=128)),
                ('char_id', models.CharField(blank=True, default='', max_length=64)),
                ('char_name', models.CharField(blank=True, default='', max_length=128)),
                ('rarity', models.IntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('gacha_ts', models.BigIntegerField(blank=True, null=True)),
                ('seq_id', models.IntegerField(db_index=True)),
                ('source_pool_type', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='core.importsession')),
            ],
        ),
    ]
