# Generated by Django 6.0.1 on 2026-02-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('aliases', models.TextField(blank=True, default='')),
                ('static_icon_path', models.CharField(help_text='Path in static/, e.g. img/characters/ember.png', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pool_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('six_star_characters', models.ManyToManyField(blank=True, related_name='banners', to='core.staticcharacter')),
                ('top_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_for_banners', to='core.staticcharacter')),
            ],
            options={
                'ordering': ('-start_date', 'pool_id'),
            },
        ),
    ]
