# Generated by Django 6.0.1 on 2026-02-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staticcharacter_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionTopStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_session_id', models.IntegerField(db_index=True)),
                ('version_major', models.PositiveIntegerField(db_index=True, default=0)),
                ('version_minor', models.PositiveIntegerField(db_index=True, default=0)),
                ('version_label', models.CharField(db_index=True, max_length=32)),
                ('tracked_characters_count', models.PositiveIntegerField(default=0)),
                ('total_top_drops', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(default=list)),
            ],
            options={
                'ordering': ('-version_major', '-version_minor', '-created_at', '-id'),
            },
        ),
    ]
