# Generated by Django 6.0.1 on 2026-02-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_versiontopstatssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
