# Generated by Django 4.2.28 on 2026-02-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('rarity', models.PositiveSmallIntegerField(db_index=True, default=4)),
                ('weapon_type', models.CharField(choices=[('short', 'Sword'), ('great', 'Great Sword'), ('guns', 'Hand Cannon'), ('polearms', 'Polearm'), ('orbiters', 'Arts Device')], db_index=True, default='short', max_length=16)),
                ('icon_name', models.CharField(max_length=255)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('description_i18n', models.JSONField(blank=True, default=dict)),
                ('atk_min', models.PositiveIntegerField(default=0)),
                ('atk_max', models.PositiveIntegerField(default=0)),
                ('skills_min_i18n', models.JSONField(blank=True, default=dict)),
                ('skills_max_i18n', models.JSONField(blank=True, default=dict)),
                ('skills_full_i18n', models.JSONField(blank=True, default=dict)),
                ('operators_i18n', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-rarity', 'key'),
            },
        ),
    ]
