"""Lightweight application localization layer.

The project intentionally uses a code-based translation map instead of Django
`.po` catalogs to keep deployment simple for a small self-hosted app.
"""

from __future__ import annotations

from typing import Dict, List


DEFAULT_LANGUAGE = "ru"
SITE_LANGUAGE_SESSION_KEY = "site_language"
SITE_LANGUAGE_COOKIE_KEY = "site_language"

LANGUAGE_OPTIONS: List[Dict[str, str]] = [
    {"code": "ru", "label": "Русский"},
    {"code": "en", "label": "English"},
    {"code": "de", "label": "Deutsch"},
    {"code": "zh-hans", "label": "简体中文"},
    {"code": "ja", "label": "日本語"},
]

SUPPORTED_LANGUAGES = {item["code"] for item in LANGUAGE_OPTIONS}


TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "ru": {
        "menu.home": "Главная",
        "menu.characters": "Персонажи",
        "menu.weapons": "Оружия",
        "menu.import": "Импорт круток",
        "menu.settings": "Настройки",
        "footer.privacy": "Политика конфиденциальности",
        "footer.cookies": "Cookie",
        "footer.aria": "Подвал сайта",
        "language.selector": "Язык интерфейса",
        "title.dashboard": "Счётчик круток",
        "title.characters": "Персонажи",
        "title.weapons": "Оружия",
        "title.settings": "Настройки",
        "title.import": "Импорт истории круток",
        "title.privacy": "Политика конфиденциальности",
        "title.cookies": "Политика Cookie",
        "dashboard.title": "Счётчик круток",
        "dashboard.action.import": "Импортировать",
        "dashboard.action.settings": "Настройки",
        "dashboard.total_wishes": "Молитв за всё время",
        "dashboard.pity6": "6★ Гарант",
        "dashboard.pity5": "5★ Гарант",
        "dashboard.pity_suffix": "на {limit} крутке · осталось {left}",
        "dashboard.filter.all": "Все",
        "dashboard.table.name": "Имя",
        "dashboard.table.date": "Дата",
        "dashboard.table.guarantee": "Гарант",
        "dashboard.empty": "Нет данных. Выполните импорт истории.",
        "dashboard.history.collapse": "Свернуть историю",
        "dashboard.history.expand": "Показать историю",
        "dashboard.pool.character": "Баннер персонажа",
        "dashboard.pool.standard": "Стандартный баннер",
        "dashboard.pool.beginner": "Баннер новичка",
        "characters.title": "Персонажи",
        "characters.obtained": "Получено",
        "characters.missing": "Не получено",
        "characters.rarity": "Редкость: {rarity}★",
        "characters.date_unknown": "дата неизвестна",
        "characters.unknown_name": "Неизвестно",
        "weapons.title": "Оружия",
        "weapons.total": "Всего оружий: {count}",
        "weapons.rarity": "Редкость: {rarity}★",
        "weapons.empty": "Иконки оружия не найдены.",
        "character.element.heat": "Тепло",
        "character.element.cryo": "Крио",
        "character.element.electric": "Электричество",
        "character.element.nature": "Природа",
        "character.element.physical": "Физический",
        "character.weapon.short": "Меч",
        "character.weapon.great": "Двуручный меч",
        "character.weapon.guns": "Ручная пушка",
        "character.weapon.polearms": "Копьё",
        "character.weapon.orbiters": "Артс-устройство",
        "character.role.caster": "Заклинатель",
        "character.role.defender": "Защитник",
        "character.role.guard": "Страж",
        "character.role.striker": "Нападающий",
        "character.role.support": "Поддержка",
        "character.role.vanguard": "Авангард",
        "settings.title": "Настройки",
        "settings.history.title": "История",
        "settings.history.desc": "Экспортируйте всю историю импортов в JSON или восстановите её из файла.",
        "settings.history.export": "Экспорт JSON",
        "settings.history.import_label": "JSON-файл для импорта",
        "settings.history.import_btn": "Импорт JSON",
        "settings.history.hint": "Импорт добавляет записи как новые и не удаляет текущие данные.",
        "settings.support.title": "Поддержка проекта",
        "settings.support.desc": "Если приложение полезно, можно поддержать разработку.",
        "settings.support.donate": "Пожертвовать",
        "settings.repo.title": "Официальный репозиторий",
        "settings.repo.desc": "Исходники и обновления доступны на GitHub.",
        "settings.repo.open": "Открыть GitHub",
        "settings.cloud.title": "Облако",
        "settings.cloud.desc": "Google Drive и Яндекс Диск работают по OAuth: подключаете аккаунт один раз, дальше синхронизация в автоматическую папку.",
        "settings.cloud.folder_file": "Папка: {folder} · Файл: {file}.",
        "settings.cloud.connected": "Подключено",
        "settings.cloud.disconnected": "Не подключено",
        "settings.cloud.not_configured": "Провайдер не настроен на сервере.",
        "settings.cloud.env_required": "Нужны переменные окружения: {hint}.",
        "settings.cloud.connect_hint": "Подключите аккаунт, чтобы включить автоматическую синхронизацию.",
        "settings.cloud.connect_btn": "Войти через {provider}",
        "settings.cloud.sync_hint": "Синхронизация выполняется автоматически в {path}.",
        "settings.cloud.expiring_hint": "OAuth-сессия скоро истечёт, при синхронизации токен обновится автоматически.",
        "settings.cloud.sync_to": "Синхронизировать в облако",
        "settings.cloud.sync_from": "Синхронизировать из облака",
        "settings.cloud.disconnect": "Отключить",
        "settings.cloud.url.title": "Импорт из других облаков по ссылке",
        "settings.cloud.url.desc": "Если сервис умеет отдавать прямую ссылку на JSON, можно импортировать без OAuth.",
        "settings.cloud.url.label": "Прямая ссылка на JSON",
        "settings.cloud.url.btn": "Импорт по ссылке",
        "privacy.title": "Политика конфиденциальности",
        "privacy.updated": "Дата обновления: 09.02.2026",
        "privacy.p1": "EndfieldPass хранит импортированные данные локально в вашей базе и в браузере (настройки формы). Мы не запрашиваем данные аккаунта напрямую, кроме параметров, которые вы самостоятельно вставляете для импорта истории.",
        "privacy.p2": "Какие данные могут обрабатываться:",
        "privacy.i1": "История круток (персонаж, редкость, время, пул и служебные поля импорта).",
        "privacy.i2": "Параметры импорта (server/lang/token), если вы их указываете.",
        "privacy.i3": "Технические настройки интерфейса в localStorage.",
        "privacy.p3": "Передача данных третьим лицам не выполняется в рамках локального использования приложения.",
        "cookies.title": "Политика Cookie",
        "cookies.updated": "Дата обновления: 09.02.2026",
        "cookies.p1": "EndfieldPass использует только технические cookie и локальное хранилище браузера для работы интерфейса.",
        "cookies.p2": "Что используется:",
        "cookies.i1": "Сессионные cookie Django (например, для CSRF и корректной работы форм).",
        "cookies.i2": "localStorage для сохранения пользовательских настроек формы импорта.",
        "cookies.p3": "Маркетинговые и рекламные cookie не используются.",
        "cookies.p4": "Вы можете очистить cookie и localStorage в настройках браузера в любой момент.",
        "import.title": "Импорт истории круток",
        "import.hero.title": "Синхронизируйте историю молитв с аккаунтом",
        "import.hero.desc": "Вставьте ссылку на страницу истории, а token/server/lang подтянутся автоматически.",
        "import.hero.warn": "Если автопарсинг не сработал — заполните token и server id вручную.",
        "import.mode.auto": "Автоматический",
        "import.mode.manual": "Ручной",
        "import.page_url": "Ссылка на страницу истории",
        "import.token.placeholder": "Подставится из ссылки",
        "import.run": "Запустить импорт",
        "import.guide.title": "Инструкция",
        "import.platform.aria": "Выбор платформы",
        "import.platform.windows": "ПК (Windows)",
        "import.platform.step1": "Выберите свой сервер.",
        "import.platform.step2": "Запустите Arknights: Endfield на ПК.",
        "import.platform.step3": "Откройте историю молитв в игре и дождитесь полной загрузки.",
        "import.platform.step4": "Откройте Windows PowerShell.",
        "import.platform.step5": "Скопируйте и вставьте скрипт ниже в окно PowerShell.",
        "import.platform.step6": "Нажмите ENTER, после чего ссылка будет скопирована в буфер обмена.",
        "import.platform.step7": "Вставьте полученный текст в поле выше и запустите импорт.",
        "import.copy": "Копировать",
        "import.copied": "Скопировано",
        "import.copy_error": "Ошибка",
        "import.android_soon": "Android: скоро",
        "import.ios_soon": "iOS: скоро",
        "import.platform.soon_desc": "Сейчас импорт поддерживается только для ПК (Windows). Добавим {platform} в одном из следующих обновлений.",
        "import.result.none": "Записей пока нет.",
        "import.loading.prepare": "Подготавливаем импорт...",
        "import.loading.hint1": "Подгружаем вашу историю круток...",
        "import.loading.hint2": "Она очень большая, но мы справляемся.",
        "import.loading.hint3": "Считаем количество потраченных денег...",
        "import.loading.hint4": "Проверяем дубликаты и приводим данные к порядку.",
        "import.loading.hint5": "Сверяем баннеры, даты и серверы.",
        "import.loading.hint6": "Крутим шестерёнки удачи... почти готово.",
        "import.loading.hint7": "Нормализуем названия персонажей и оружия.",
        "import.loading.hint8": "Подготавливаем графики, чтобы выглядело красиво.",
        "import.loading.hint9": "Собираем аккуратную историю без мусора и дублей.",
        "import.loading.hint10": "Проверяем, где кончился pity и где начался топ-дроп.",
        "import.loading.hint11": "Считаем редкости и помечаем ключевые дропы.",
        "import.loading.hint12": "Финальные штрихи: ещё пара секунд.",
        "import.error.title": "Проверьте данные импорта",
        "import.error.default": "Не удалось выполнить импорт.",
        "import.error.retry": "Не удалось выполнить импорт. Попробуйте ещё раз.",
        "import.error.manual_required": "Для ручного импорта заполните token и server ID.",
        "import.error.auto_missing": "Не удалось извлечь token и server ID из ссылки. Вставьте полную ссылку истории или используйте ручной режим.",
        "import.error.bad_json": "Сервер отклонил запрос. Обновите страницу и попробуйте снова.",
        "import.error.post_only": "Некорректный тип запроса. Обновите страницу и повторите импорт.",
        "import.error.need_link": "Вставьте ссылку на страницу истории для автоматического импорта.",
        "import.error.status_failed": "Не удалось получить статус импорта.",
        "import.error.processing": "Обрабатываем импорт...",
        "import.error.done_opening": "Импорт завершён. Открываем результат...",
        "import.error.import_failed": "Импорт завершился с ошибкой.",
        "import.error.invalid_session": "Сервер вернул некорректный session_id.",
        "import.error.header": "Ошибка импорта",
        "import.result.header": "Импорт #{id}",
        "import.result.status": "Статус: {status}",
        "import.result.error": "Ошибка: {error}",
        "import.result.server_lang": "Сервер: {server} | Язык: {lang}",
        "import.result.json": "JSON (pulls сессии)",
        "import.result.api": "JSON API (/api/pulls)",
        "view.error.bad_payload": "Ожидался JSON-объект.",
        "view.error.bad_format": "Формат JSON не поддерживается: отсутствует список sessions/items.",
        "view.settings.select_json": "Выберите JSON-файл для импорта.",
        "view.settings.utf8": "Файл должен быть в кодировке UTF-8.",
        "view.settings.read_json": "Не удалось прочитать JSON. Проверьте формат файла.",
        "view.settings.import_failed": "Не удалось импортировать историю.",
        "view.settings.import_error": "Импорт завершился с ошибкой.",
        "view.settings.import_done": "Импорт завершён.",
        "view.settings.counts": "Сессий: {sessions}. Записей: {pulls}.",
        "view.cloud.provider_not_configured": "{provider} не настроен.",
        "view.cloud.provider_not_configured_details": "Добавьте client id/client secret в переменные окружения сервера.",
        "view.cloud.oauth_start_failed": "Не удалось запустить OAuth-подключение.",
        "view.cloud.oauth_denied": "OAuth для {provider} отклонён.",
        "view.cloud.oauth_state_failed": "Не удалось подтвердить OAuth-сессию.",
        "view.cloud.oauth_state_details": "Некорректный state.",
        "view.cloud.oauth_code_missing": "Не удалось завершить OAuth-подключение.",
        "view.cloud.oauth_code_missing_details": "Провайдер не вернул код авторизации.",
        "view.cloud.oauth_connect_failed": "Не удалось подключить {provider}.",
        "view.cloud.oauth_connected": "{provider} подключен.",
        "view.cloud.oauth_connected_details": "OAuth-сессия активна.",
        "view.cloud.oauth_disconnected": "{provider} отключен.",
        "view.cloud.choose_sync_provider": "Выберите Google Drive или Yandex Disk.",
        "view.cloud.sync_failed": "Не удалось выполнить облачную синхронизацию.",
        "view.cloud.sync_error": "Облачная синхронизация завершилась с ошибкой.",
        "view.cloud.sync_done": "Синхронизация в облако выполнена.",
        "view.cloud.sync_done_google": "Папка: {folder}. Файл: {file}.",
        "view.cloud.sync_done_yandex": "Путь: {path}.",
        "view.cloud.choose_import_source": "Выберите источник импорта.",
        "view.cloud.url_required": "Укажите прямую ссылку на JSON-файл.",
        "view.cloud.import_failed": "Не удалось выполнить облачный импорт.",
        "view.cloud.import_bad_format": "Облачный файл имеет некорректный формат.",
        "view.cloud.import_error": "Облачный импорт завершился с ошибкой.",
        "view.cloud.import_done": "Облачный импорт завершён.",
        "view.cloud.connect_first": "Подключите {provider} через OAuth.",
        "view.cloud.server_not_configured": "{provider} не настроен на сервере. Укажите client id/client secret в переменных окружения.",
        "view.cloud.unknown_provider": "Неизвестный облачный провайдер.",
        "view.cloud.no_token": "Провайдер не вернул access token.",
    },
    "en": {
        "menu.home": "Home",
        "menu.characters": "Characters",
        "menu.weapons": "Weapons",
        "menu.import": "Import",
        "menu.settings": "Settings",
        "footer.privacy": "Privacy Policy",
        "footer.cookies": "Cookie",
        "footer.aria": "Site footer",
        "language.selector": "Interface language",
        "title.dashboard": "Wish Counter",
        "title.characters": "Characters",
        "title.weapons": "Weapons",
        "title.settings": "Settings",
        "title.import": "Wish History Import",
        "title.privacy": "Privacy Policy",
        "title.cookies": "Cookie Policy",
        "dashboard.title": "Wish Counter",
        "dashboard.action.import": "Import",
        "dashboard.action.settings": "Settings",
        "dashboard.total_wishes": "Total wishes",
        "dashboard.pity6": "6★ Pity",
        "dashboard.pity5": "5★ Pity",
        "dashboard.pity_suffix": "at pull {limit} · left {left}",
        "dashboard.filter.all": "All",
        "dashboard.table.name": "Name",
        "dashboard.table.date": "Date",
        "dashboard.table.guarantee": "Pity",
        "dashboard.empty": "No data yet. Import your history first.",
        "dashboard.history.collapse": "Collapse history",
        "dashboard.history.expand": "Show history",
        "dashboard.pool.character": "Character Banner",
        "dashboard.pool.standard": "Standard Banner",
        "dashboard.pool.beginner": "Beginner Banner",
        "characters.title": "Characters",
        "characters.obtained": "Obtained",
        "characters.missing": "Not obtained",
        "characters.rarity": "Rarity: {rarity}★",
        "characters.date_unknown": "date unknown",
        "characters.unknown_name": "Unknown",
        "weapons.title": "Weapons",
        "weapons.total": "Total weapons: {count}",
        "weapons.rarity": "Rarity: {rarity}★",
        "weapons.empty": "No weapon icons found.",
        "character.element.heat": "Heat",
        "character.element.cryo": "Cryo",
        "character.element.electric": "Electric",
        "character.element.nature": "Nature",
        "character.element.physical": "Physical",
        "character.weapon.short": "Short Weapon",
        "character.weapon.great": "Great Weapon",
        "character.weapon.guns": "Guns",
        "character.weapon.polearms": "Polearms",
        "character.weapon.orbiters": "Orbiters",
        "character.role.caster": "Caster",
        "character.role.defender": "Defender",
        "character.role.guard": "Guard",
        "character.role.striker": "Striker",
        "character.role.support": "Support",
        "character.role.vanguard": "Vanguard",
        "settings.title": "Settings",
        "settings.history.title": "History",
        "settings.history.desc": "Export all import history to JSON or restore it from file.",
        "settings.history.export": "Export JSON",
        "settings.history.import_label": "JSON file to import",
        "settings.history.import_btn": "Import JSON",
        "settings.history.hint": "Import adds records and does not remove existing data.",
        "settings.support.title": "Support the Project",
        "settings.support.desc": "If this app is useful, you can support development.",
        "settings.support.donate": "Donate",
        "settings.repo.title": "Official Repository",
        "settings.repo.desc": "Source code and updates are available on GitHub.",
        "settings.repo.open": "Open GitHub",
        "settings.cloud.title": "Cloud",
        "settings.cloud.desc": "Google Drive and Yandex Disk use OAuth: connect once, then sync to an automatic folder.",
        "settings.cloud.folder_file": "Folder: {folder} · File: {file}.",
        "settings.cloud.connected": "Connected",
        "settings.cloud.disconnected": "Not connected",
        "settings.cloud.not_configured": "Provider is not configured on server.",
        "settings.cloud.env_required": "Required environment variables: {hint}.",
        "settings.cloud.connect_hint": "Connect your account to enable automatic sync.",
        "settings.cloud.connect_btn": "Sign in with {provider}",
        "settings.cloud.sync_hint": "Sync uses {path} automatically.",
        "settings.cloud.expiring_hint": "OAuth session expires soon. Token refresh is automatic during sync.",
        "settings.cloud.sync_to": "Sync to cloud",
        "settings.cloud.sync_from": "Sync from cloud",
        "settings.cloud.disconnect": "Disconnect",
        "settings.cloud.url.title": "Import from other clouds by URL",
        "settings.cloud.url.desc": "If a service can provide a direct JSON URL, import works without OAuth.",
        "settings.cloud.url.label": "Direct JSON URL",
        "settings.cloud.url.btn": "Import by URL",
        "privacy.title": "Privacy Policy",
        "privacy.updated": "Updated: February 9, 2026",
        "privacy.p1": "EndfieldPass stores imported data locally in your database and browser (form settings). We do not request account data directly except parameters you provide for history import.",
        "privacy.p2": "What data may be processed:",
        "privacy.i1": "Wish history (character, rarity, time, pool and service import fields).",
        "privacy.i2": "Import parameters (server/lang/token), if you provide them.",
        "privacy.i3": "Technical UI settings in localStorage.",
        "privacy.p3": "No transfer to third parties is performed in local app usage.",
        "cookies.title": "Cookie Policy",
        "cookies.updated": "Updated: February 9, 2026",
        "cookies.p1": "EndfieldPass uses only technical cookies and browser local storage for UI functionality.",
        "cookies.p2": "What is used:",
        "cookies.i1": "Django session cookies (for CSRF and form operation).",
        "cookies.i2": "localStorage for import form preferences.",
        "cookies.p3": "No marketing or advertising cookies are used.",
        "cookies.p4": "You can clear cookies and localStorage in browser settings at any time.",
        "import.title": "Wish History Import",
        "import.hero.title": "Sync your wish history with account",
        "import.hero.desc": "Paste the history page URL, token/server/lang will be parsed automatically.",
        "import.hero.warn": "If auto parsing fails, fill token and server id manually.",
        "import.mode.auto": "Automatic",
        "import.mode.manual": "Manual",
        "import.page_url": "History page URL",
        "import.token.placeholder": "Will be parsed from URL",
        "import.run": "Start import",
        "import.guide.title": "Instruction",
        "import.platform.aria": "Platform selection",
        "import.platform.windows": "PC (Windows)",
        "import.platform.step1": "Choose your server.",
        "import.platform.step2": "Launch Arknights: Endfield on PC.",
        "import.platform.step3": "Open wish history and wait for full load.",
        "import.platform.step4": "Open Windows PowerShell.",
        "import.platform.step5": "Copy and paste script below into PowerShell.",
        "import.platform.step6": "Press ENTER and URL will be copied to clipboard.",
        "import.platform.step7": "Paste the copied text above and start import.",
        "import.copy": "Copy",
        "import.copied": "Copied",
        "import.copy_error": "Error",
        "import.android_soon": "Android: soon",
        "import.ios_soon": "iOS: soon",
        "import.platform.soon_desc": "Currently import is available only for PC (Windows). {platform} support will come soon.",
        "import.result.none": "No records yet.",
        "import.loading.prepare": "Preparing import...",
        "import.loading.hint1": "Loading your wish history...",
        "import.loading.hint2": "It's large, but we are processing it.",
        "import.loading.hint3": "Calculating spent pulls...",
        "import.loading.hint4": "Checking duplicates and normalizing data.",
        "import.loading.hint5": "Matching banners, dates, and sequence ids.",
        "import.loading.hint6": "Turning luck gears... almost there.",
        "import.loading.hint7": "Normalizing character and weapon names.",
        "import.loading.hint8": "Preparing charts so everything looks clean.",
        "import.loading.hint9": "Building a tidy history without duplicate noise.",
        "import.loading.hint10": "Checking where pity ended and big drops started.",
        "import.loading.hint11": "Counting rarities and marking key drops.",
        "import.loading.hint12": "Final touches: just a little more.",
        "import.error.title": "Check import data",
        "import.error.default": "Import failed.",
        "import.error.retry": "Import failed. Please try again.",
        "import.error.manual_required": "Fill token and server ID for manual import.",
        "import.error.auto_missing": "Could not extract token and server ID from URL. Paste full history URL or use manual mode.",
        "import.error.bad_json": "Server rejected request. Refresh page and try again.",
        "import.error.post_only": "Invalid request type. Refresh page and retry import.",
        "import.error.need_link": "Paste history page URL for automatic import.",
        "import.error.status_failed": "Failed to fetch import status.",
        "import.error.processing": "Processing import...",
        "import.error.done_opening": "Import complete. Opening result...",
        "import.error.import_failed": "Import finished with error.",
        "import.error.invalid_session": "Server returned invalid session_id.",
        "import.error.header": "Import error",
        "import.result.header": "Import #{id}",
        "import.result.status": "Status: {status}",
        "import.result.error": "Error: {error}",
        "import.result.server_lang": "Server: {server} | Lang: {lang}",
        "import.result.json": "JSON (session pulls)",
        "import.result.api": "JSON API (/api/pulls)",
        "view.error.bad_payload": "Expected JSON object.",
        "view.error.bad_format": "Unsupported JSON format: sessions/items list is missing.",
        "view.settings.select_json": "Choose JSON file for import.",
        "view.settings.utf8": "File must use UTF-8 encoding.",
        "view.settings.read_json": "Could not parse JSON. Check file format.",
        "view.settings.import_failed": "Failed to import history.",
        "view.settings.import_error": "Import finished with an error.",
        "view.settings.import_done": "Import completed.",
        "view.settings.counts": "Sessions: {sessions}. Records: {pulls}.",
        "view.cloud.provider_not_configured": "{provider} is not configured.",
        "view.cloud.provider_not_configured_details": "Add client id/client secret to server environment variables.",
        "view.cloud.oauth_start_failed": "Failed to start OAuth connection.",
        "view.cloud.oauth_denied": "OAuth for {provider} was denied.",
        "view.cloud.oauth_state_failed": "Failed to verify OAuth session.",
        "view.cloud.oauth_state_details": "Invalid state.",
        "view.cloud.oauth_code_missing": "Failed to complete OAuth connection.",
        "view.cloud.oauth_code_missing_details": "Provider did not return authorization code.",
        "view.cloud.oauth_connect_failed": "Failed to connect {provider}.",
        "view.cloud.oauth_connected": "{provider} connected.",
        "view.cloud.oauth_connected_details": "OAuth session is active.",
        "view.cloud.oauth_disconnected": "{provider} disconnected.",
        "view.cloud.choose_sync_provider": "Choose Google Drive or Yandex Disk.",
        "view.cloud.sync_failed": "Cloud sync failed.",
        "view.cloud.sync_error": "Cloud sync finished with an error.",
        "view.cloud.sync_done": "Cloud sync completed.",
        "view.cloud.sync_done_google": "Folder: {folder}. File: {file}.",
        "view.cloud.sync_done_yandex": "Path: {path}.",
        "view.cloud.choose_import_source": "Choose import source.",
        "view.cloud.url_required": "Provide a direct JSON URL.",
        "view.cloud.import_failed": "Cloud import failed.",
        "view.cloud.import_bad_format": "Cloud file has invalid format.",
        "view.cloud.import_error": "Cloud import finished with an error.",
        "view.cloud.import_done": "Cloud import completed.",
        "view.cloud.connect_first": "Connect {provider} via OAuth first.",
        "view.cloud.server_not_configured": "{provider} is not configured on server. Set client id/client secret environment variables.",
        "view.cloud.unknown_provider": "Unknown cloud provider.",
        "view.cloud.no_token": "Provider did not return access token.",
    },
    "de": {
        "menu.home": "Startseite",
        "menu.characters": "Charaktere",
        "menu.weapons": "Waffen",
        "menu.import": "Import",
        "menu.settings": "Einstellungen",
        "footer.privacy": "Datenschutz",
        "footer.cookies": "Cookies",
        "footer.aria": "Seitenfuß",
        "language.selector": "Sprache",
        "title.dashboard": "Wish-Zähler",
        "title.characters": "Charaktere",
        "title.weapons": "Waffen",
        "title.settings": "Einstellungen",
        "title.import": "Import der Wunsch-Historie",
        "title.privacy": "Datenschutz",
        "title.cookies": "Cookie-Richtlinie",
        "dashboard.title": "Wish-Zähler",
        "dashboard.action.import": "Importieren",
        "dashboard.action.settings": "Einstellungen",
        "dashboard.total_wishes": "Wünsche insgesamt",
        "dashboard.pity6": "6★ Pity",
        "dashboard.pity5": "5★ Pity",
        "dashboard.pity_suffix": "bei Pull {limit} · verbleibend {left}",
        "dashboard.filter.all": "Alle",
        "dashboard.table.name": "Name",
        "dashboard.table.date": "Datum",
        "dashboard.table.guarantee": "Pity",
        "dashboard.empty": "Keine Daten. Importiere zuerst die Historie.",
        "dashboard.history.collapse": "Historie einklappen",
        "dashboard.history.expand": "Historie anzeigen",
        "dashboard.pool.character": "Charakter-Banner",
        "dashboard.pool.standard": "Standard-Banner",
        "dashboard.pool.beginner": "Anfänger-Banner",
        "characters.title": "Charaktere",
        "characters.obtained": "Erhalten",
        "characters.missing": "Nicht erhalten",
        "characters.rarity": "Seltenheit: {rarity}★",
        "characters.date_unknown": "Datum unbekannt",
        "characters.unknown_name": "Unbekannt",
        "weapons.title": "Waffen",
        "weapons.total": "Waffen gesamt: {count}",
        "weapons.rarity": "Seltenheit: {rarity}★",
        "weapons.empty": "Keine Waffen-Icons gefunden.",
    },
    "zh-hans": {
        "menu.home": "主页",
        "menu.characters": "角色",
        "menu.weapons": "武器",
        "menu.import": "导入",
        "menu.settings": "设置",
        "footer.privacy": "隐私政策",
        "footer.cookies": "Cookie",
        "footer.aria": "页脚",
        "language.selector": "界面语言",
        "title.dashboard": "抽卡统计",
        "title.characters": "角色",
        "title.weapons": "武器",
        "title.settings": "设置",
        "title.import": "抽卡记录导入",
        "title.privacy": "隐私政策",
        "title.cookies": "Cookie 政策",
        "dashboard.title": "抽卡统计",
        "dashboard.action.import": "导入",
        "dashboard.action.settings": "设置",
        "dashboard.total_wishes": "总抽卡次数",
        "dashboard.pity6": "6★ 保底",
        "dashboard.pity5": "5★ 保底",
        "dashboard.pity_suffix": "第 {limit} 抽 · 剩余 {left}",
        "dashboard.filter.all": "全部",
        "dashboard.table.name": "名称",
        "dashboard.table.date": "日期",
        "dashboard.table.guarantee": "保底",
        "dashboard.empty": "暂无数据，请先导入历史记录。",
        "dashboard.history.collapse": "收起历史",
        "dashboard.history.expand": "展开历史",
        "dashboard.pool.character": "角色卡池",
        "dashboard.pool.standard": "常驻卡池",
        "dashboard.pool.beginner": "新手卡池",
        "characters.title": "角色",
        "characters.obtained": "已获得",
        "characters.missing": "未获得",
        "characters.rarity": "稀有度：{rarity}★",
        "characters.date_unknown": "日期未知",
        "characters.unknown_name": "未知",
        "weapons.title": "武器",
        "weapons.total": "武器总数：{count}",
        "weapons.rarity": "稀有度：{rarity}★",
        "weapons.empty": "未找到武器图标。",
    },
    "ja": {
        "menu.home": "ホーム",
        "menu.characters": "キャラクター",
        "menu.weapons": "武器",
        "menu.import": "インポート",
        "menu.settings": "設定",
        "footer.privacy": "プライバシーポリシー",
        "footer.cookies": "Cookie",
        "footer.aria": "フッター",
        "language.selector": "表示言語",
        "title.dashboard": "ガチャカウンター",
        "title.characters": "キャラクター",
        "title.weapons": "武器",
        "title.settings": "設定",
        "title.import": "履歴インポート",
        "title.privacy": "プライバシーポリシー",
        "title.cookies": "Cookie ポリシー",
        "dashboard.title": "ガチャカウンター",
        "dashboard.action.import": "インポート",
        "dashboard.action.settings": "設定",
        "dashboard.total_wishes": "総ガチャ回数",
        "dashboard.pity6": "6★ 天井",
        "dashboard.pity5": "5★ 天井",
        "dashboard.pity_suffix": "{limit}連天井 · 残り {left}",
        "dashboard.filter.all": "すべて",
        "dashboard.table.name": "名前",
        "dashboard.table.date": "日付",
        "dashboard.table.guarantee": "天井",
        "dashboard.empty": "データがありません。先に履歴をインポートしてください。",
        "dashboard.history.collapse": "履歴を閉じる",
        "dashboard.history.expand": "履歴を表示",
        "dashboard.pool.character": "キャラバナー",
        "dashboard.pool.standard": "通常バナー",
        "dashboard.pool.beginner": "初心者バナー",
        "characters.title": "キャラクター",
        "characters.obtained": "所持済み",
        "characters.missing": "未所持",
        "characters.rarity": "レア度: {rarity}★",
        "characters.date_unknown": "日付不明",
        "characters.unknown_name": "不明",
        "weapons.title": "武器",
        "weapons.total": "武器合計: {count}",
        "weapons.rarity": "レア度: {rarity}★",
        "weapons.empty": "武器アイコンが見つかりません。",
    },
}

# Additional keys introduced by UI updates. Kept separately to avoid large edits
# in the base translation blocks and to simplify future backports.
EXTRA_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "ru": {
        "dashboard.weapon_permanent.title": "Постоянные поставки",
        "dashboard.weapon_permanent.help": "Левая цифра - общее число круток, правая - гарант 6★.",
        "dashboard.weapon_permanent.pool.solid_ice": "Крепкий лёд",
        "dashboard.weapon_permanent.pool.cosmic_voice": "Космический голос",
        "dashboard.weapon_permanent.pool.far_expedition": "Дальняя экспедиция",
        "dashboard.weapon_permanent.pool.high_peak": "Высокий пик",
        "dashboard.weapon_permanent.pool.thunder_roll": "Громовой раскат",
        "dashboard.weapon6": "6★ Оружие",
        "dashboard.weapon_pulls": "Крутки оружия",
        "dashboard.pool.weapon": "Баннер оружия",
        "dashboard.pool.unknown": "Неизвестный баннер",
        "dashboard.pool.generic": "Баннер",
        "dashboard.emergency_recruitment": "Экстренная вербовка",
        "dashboard.pulls_word": "круток",
        "dashboard.pity4_short": "4★",
        "dashboard.chart.title": "Статистика круток по датам",
        "dashboard.chart.zoom_in": "Увеличить график",
        "dashboard.chart.zoom_out": "Уменьшить график",
        "dashboard.chart.aria": "График круток по датам",
        "characters.title_help": "Список показывает персонажей и их потенциал по вашей истории круток.",
        "characters.potential": "Потенциал",
        "import.manual.token": "Токен (u8_token)",
        "import.manual.server_id": "ID сервера",
        "import.manual.language": "Язык",
        "import.platform.linux": "Linux",
        "import.platform.android": "Android",
        "import.platform.ios": "iOS",
        "import.platform.beta": "Beta",
        "import.platform.linux.step2": "Запустите Arknights: Endfield на Linux.",
        "import.platform.linux.step4": "Откройте терминал.",
        "import.platform.linux.step5": "Скопируйте и вставьте скрипт ниже в терминал.",
        "import.platform.android.step1": "Установите Shizuku и LogFox.",
        "import.platform.android.step2": "Включите беспроводную отладку и выполните сопряжение с Shizuku.",
        "import.platform.android.step3": "Запустите службу Shizuku, затем выберите Shizuku logger в LogFox.",
        "import.platform.android.step4": "Записывайте логи, открывая историю перехватов в игре.",
        "import.platform.android.step5": "Найдите в логах слово \"token\" и скопируйте его значение.",
        "import.platform.ios.step1": "Установите Stream из App Store.",
        "import.platform.ios.step2": "Разрешите настройку профиля VPN в настройках iOS.",
        "import.platform.ios.step3": "Установите и подтвердите сертификат Stream (перехват HTTPS-трафика).",
        "import.platform.ios.step4": "Откройте историю перехвата Endfield и оставьте её видимой.",
        "import.platform.ios.step5": "Запустите перехват в Stream и обновите историю в игре.",
        "import.platform.ios.step6": "Остановите перехват и скопируйте URL-адрес запроса с ef-webview.gryphline.com.",
        "import.platform.soon_desc.android": "Пока импорт доступен только на ПК. Поддержка Android появится позже.",
        "import.platform.soon_desc.ios": "Пока импорт доступен только на ПК. Поддержка iOS появится позже.",
        "import.result.table.seq": "№",
        "import.result.table.pool": "Баннер",
        "import.result.table.rarity": "Редкость",
        "import.result.table.name": "Имя",
        "import.result.table.free": "Бесплатно",
        "import.result.table.new": "Новое",
        "import.result.table.ts": "Время",
        "settings.cloud.yandex_unavailable": "Yandex Disk: временно недоступен.",
        "common.ok": "ОК",
    },
    "en": {
        "dashboard.weapon_permanent.title": "Permanent Supplies",
        "dashboard.weapon_permanent.help": "Left number = total pulls, right number = 6★ pity.",
        "dashboard.weapon_permanent.pool.solid_ice": "Solid Ice",
        "dashboard.weapon_permanent.pool.cosmic_voice": "Cosmic Voice",
        "dashboard.weapon_permanent.pool.far_expedition": "Far Expedition",
        "dashboard.weapon_permanent.pool.high_peak": "High Peak",
        "dashboard.weapon_permanent.pool.thunder_roll": "Thunder Roll",
        "dashboard.weapon6": "6★ Weapon",
        "dashboard.weapon_pulls": "Weapon pulls",
        "dashboard.pool.weapon": "Weapon Banner",
        "dashboard.pool.unknown": "Unknown banner",
        "dashboard.pool.generic": "Banner",
        "dashboard.emergency_recruitment": "Emergency recruitment",
        "dashboard.pulls_word": "pulls",
        "dashboard.pity4_short": "4★",
        "dashboard.chart.title": "Pull Statistics by Date",
        "dashboard.chart.zoom_in": "Zoom in chart",
        "dashboard.chart.zoom_out": "Zoom out chart",
        "dashboard.chart.aria": "Pull history chart by date",
        "characters.title_help": "Shows characters and their potential from your pull history.",
        "characters.potential": "Potential",
        "import.manual.token": "Token (u8_token)",
        "import.manual.server_id": "Server ID",
        "import.manual.language": "Language",
        "import.platform.linux": "Linux",
        "import.platform.android": "Android",
        "import.platform.ios": "iOS",
        "import.platform.beta": "Beta",
        "import.platform.linux.step2": "Launch Arknights: Endfield on Linux.",
        "import.platform.linux.step4": "Open terminal.",
        "import.platform.linux.step5": "Copy and paste the script below into terminal.",
        "import.platform.android.step1": "Install Shizuku and LogFox.",
        "import.platform.android.step2": "Enable wireless debugging and pair it with Shizuku.",
        "import.platform.android.step3": "Start the Shizuku service, then select Shizuku logger in LogFox.",
        "import.platform.android.step4": "Record logs while opening the interceptor history in game.",
        "import.platform.android.step5": "Find the word \"token\" in logs and copy its value.",
        "import.platform.ios.step1": "Install Stream from the App Store.",
        "import.platform.ios.step2": "Allow VPN profile setup in iOS settings.",
        "import.platform.ios.step3": "Install and trust the Stream certificate (HTTPS interception).",
        "import.platform.ios.step4": "Open Endfield interception history and keep it visible.",
        "import.platform.ios.step5": "Start interception in Stream and refresh history in game.",
        "import.platform.ios.step6": "Stop interception and copy the request URL from ef-webview.gryphline.com.",
        "import.platform.soon_desc.android": "Import is currently available on PC only. Android support is coming soon.",
        "import.platform.soon_desc.ios": "Import is currently available on PC only. iOS support is coming soon.",
        "import.result.table.seq": "No.",
        "import.result.table.pool": "Banner",
        "import.result.table.rarity": "Rarity",
        "import.result.table.name": "Name",
        "import.result.table.free": "Free",
        "import.result.table.new": "New",
        "import.result.table.ts": "Time",
        "settings.cloud.yandex_unavailable": "Yandex Disk: temporarily unavailable.",
        "common.ok": "OK",
    },
    "de": {
        "dashboard.weapon_permanent.title": "Dauerhafte Lieferungen",
        "dashboard.weapon_permanent.help": "Linke Zahl = Gesamtanzahl der Ziehungen, rechte Zahl = 6★-Garantie.",
        "dashboard.weapon_permanent.pool.solid_ice": "Stabiles Eis",
        "dashboard.weapon_permanent.pool.cosmic_voice": "Kosmische Stimme",
        "dashboard.weapon_permanent.pool.far_expedition": "Ferne Expedition",
        "dashboard.weapon_permanent.pool.high_peak": "Hoher Gipfel",
        "dashboard.weapon_permanent.pool.thunder_roll": "Donnernder Aufprall",
        "dashboard.weapon6": "6★ Waffe",
        "dashboard.weapon_pulls": "Waffenzieher",
        "dashboard.pool.weapon": "Waffenbanner",
        "dashboard.pool.unknown": "Unbekanntes Banner",
        "dashboard.pool.generic": "Banner",
        "dashboard.emergency_recruitment": "Notfallrekrutierung",
        "dashboard.pulls_word": "Ziehungen",
        "dashboard.pity4_short": "4★",
        "dashboard.chart.title": "Ziehungsstatistik nach Datum",
        "dashboard.chart.zoom_in": "Diagramm vergrößern",
        "dashboard.chart.zoom_out": "Diagramm verkleinern",
        "dashboard.chart.aria": "Ziehungsverlauf nach Datum",
        "characters.title_help": "Zeigt Charaktere und ihr Potenzial basierend auf deiner Historie.",
        "characters.potential": "Potenzial",
        "import.manual.token": "Token (u8_token)",
        "import.manual.server_id": "Server-ID",
        "import.manual.language": "Sprache",
        "import.platform.linux": "Linux",
        "import.platform.android": "Android",
        "import.platform.ios": "iOS",
        "import.platform.beta": "Beta",
        "import.platform.linux.step2": "Starte Arknights: Endfield unter Linux.",
        "import.platform.linux.step4": "Öffne das Terminal.",
        "import.platform.linux.step5": "Kopiere das Skript unten ins Terminal und führe es aus.",
        "import.platform.android.step1": "Installiere Shizuku und LogFox.",
        "import.platform.android.step2": "Aktiviere Wireless-Debugging und kopple es mit Shizuku.",
        "import.platform.android.step3": "Starte den Shizuku-Dienst und wähle dann in LogFox \"Shizuku logger\".",
        "import.platform.android.step4": "Zeichne Logs auf, während du die Abfang-Historie im Spiel öffnest.",
        "import.platform.android.step5": "Suche im Log nach \"token\" und kopiere den Wert.",
        "import.platform.ios.step1": "Installiere Stream aus dem App Store.",
        "import.platform.ios.step2": "Erlaube die VPN-Profil-Einrichtung in den iOS-Einstellungen.",
        "import.platform.ios.step3": "Installiere und bestätige das Stream-Zertifikat (HTTPS-Mitschnitt).",
        "import.platform.ios.step4": "Öffne die Endfield-Abfang-Historie und lasse sie sichtbar.",
        "import.platform.ios.step5": "Starte den Mitschnitt in Stream und aktualisiere die Historie im Spiel.",
        "import.platform.ios.step6": "Stoppe den Mitschnitt und kopiere die Request-URL von ef-webview.gryphline.com.",
        "import.platform.soon_desc.android": "Import ist aktuell nur am PC verfügbar. Android folgt bald.",
        "import.platform.soon_desc.ios": "Import ist aktuell nur am PC verfügbar. iOS folgt bald.",
        "import.result.table.seq": "Nr.",
        "import.result.table.pool": "Banner",
        "import.result.table.rarity": "Seltenheit",
        "import.result.table.name": "Name",
        "import.result.table.free": "Kostenlos",
        "import.result.table.new": "Neu",
        "import.result.table.ts": "Zeit",
        "settings.cloud.yandex_unavailable": "Yandex Disk: vorübergehend nicht verfügbar.",
        "common.ok": "OK",
    },
    "zh-hans": {
        "dashboard.weapon_permanent.title": "常驻补给",
        "dashboard.weapon_permanent.help": "左侧数字为总抽数，右侧数字为 6★ 保底。",
        "dashboard.weapon_permanent.pool.solid_ice": "坚冰锻造",
        "dashboard.weapon_permanent.pool.cosmic_voice": "宇宙回响",
        "dashboard.weapon_permanent.pool.far_expedition": "远行探索",
        "dashboard.weapon_permanent.pool.high_peak": "高峰试炼",
        "dashboard.weapon_permanent.pool.thunder_roll": "雷霆轰鸣",
        "dashboard.weapon6": "6★ 武器",
        "dashboard.weapon_pulls": "武器抽数",
        "dashboard.pool.weapon": "武器卡池",
        "dashboard.pool.unknown": "未知卡池",
        "dashboard.pool.generic": "卡池",
        "dashboard.emergency_recruitment": "紧急招募",
        "dashboard.pulls_word": "抽",
        "dashboard.pity4_short": "4★",
        "dashboard.chart.title": "按日期统计抽卡",
        "dashboard.chart.zoom_in": "放大图表",
        "dashboard.chart.zoom_out": "缩小图表",
        "dashboard.chart.aria": "按日期统计的抽卡图表",
        "characters.title_help": "根据你的抽卡记录显示角色及其潜能。",
        "characters.potential": "潜能",
        "import.manual.token": "令牌 (u8_token)",
        "import.manual.server_id": "服务器 ID",
        "import.manual.language": "语言",
        "import.platform.linux": "Linux",
        "import.platform.android": "Android",
        "import.platform.ios": "iOS",
        "import.platform.beta": "Beta",
        "import.platform.linux.step2": "在 Linux 上启动 Arknights: Endfield。",
        "import.platform.linux.step4": "打开终端。",
        "import.platform.linux.step5": "复制下方脚本并粘贴到终端执行。",
        "import.platform.android.step1": "安装 Shizuku 和 LogFox。",
        "import.platform.android.step2": "开启无线调试，并与 Shizuku 配对。",
        "import.platform.android.step3": "启动 Shizuku 服务，然后在 LogFox 中选择 Shizuku logger。",
        "import.platform.android.step4": "在游戏里打开拦截记录时开始记录日志。",
        "import.platform.android.step5": "在日志中查找 \"token\" 并复制其值。",
        "import.platform.ios.step1": "从 App Store 安装 Stream。",
        "import.platform.ios.step2": "在 iOS 设置中允许配置 VPN 描述文件。",
        "import.platform.ios.step3": "安装并信任 Stream 证书（用于 HTTPS 抓包）。",
        "import.platform.ios.step4": "打开 Endfield 抓包历史并保持可见。",
        "import.platform.ios.step5": "在 Stream 中开始抓包，并在游戏内刷新历史记录。",
        "import.platform.ios.step6": "停止抓包，并复制来自 ef-webview.gryphline.com 的请求 URL。",
        "import.platform.soon_desc.android": "目前仅支持 PC 导入，Android 即将支持。",
        "import.platform.soon_desc.ios": "目前仅支持 PC 导入，iOS 即将支持。",
        "import.result.table.seq": "序号",
        "import.result.table.pool": "卡池",
        "import.result.table.rarity": "稀有度",
        "import.result.table.name": "名称",
        "import.result.table.free": "免费",
        "import.result.table.new": "新获取",
        "import.result.table.ts": "时间",
        "settings.cloud.yandex_unavailable": "Yandex Disk：暂时不可用。",
        "common.ok": "确定",
    },
    "ja": {
        "dashboard.weapon_permanent.title": "常設補給",
        "dashboard.weapon_permanent.help": "左の数値は総ガチャ回数、右の数値は6★天井です。",
        "dashboard.weapon_permanent.pool.solid_ice": "堅氷鍛造",
        "dashboard.weapon_permanent.pool.cosmic_voice": "コズミックボイス",
        "dashboard.weapon_permanent.pool.far_expedition": "遠征探索",
        "dashboard.weapon_permanent.pool.high_peak": "高峰試練",
        "dashboard.weapon_permanent.pool.thunder_roll": "雷鳴轟音",
        "dashboard.weapon6": "6★ 武器",
        "dashboard.weapon_pulls": "武器ガチャ回数",
        "dashboard.pool.weapon": "武器バナー",
        "dashboard.pool.unknown": "不明なバナー",
        "dashboard.pool.generic": "バナー",
        "dashboard.emergency_recruitment": "緊急募集",
        "dashboard.pulls_word": "連",
        "dashboard.pity4_short": "4★",
        "dashboard.chart.title": "日付ごとのガチャ統計",
        "dashboard.chart.zoom_in": "グラフを拡大",
        "dashboard.chart.zoom_out": "グラフを縮小",
        "dashboard.chart.aria": "日付ごとのガチャ履歴グラフ",
        "characters.title_help": "ガチャ履歴に基づくキャラと潜在を表示します。",
        "characters.potential": "潜在",
        "import.manual.token": "トークン (u8_token)",
        "import.manual.server_id": "サーバー ID",
        "import.manual.language": "言語",
        "import.platform.linux": "Linux",
        "import.platform.android": "Android",
        "import.platform.ios": "iOS",
        "import.platform.beta": "Beta",
        "import.platform.linux.step2": "Linux で Arknights: Endfield を起動します。",
        "import.platform.linux.step4": "ターミナルを開きます。",
        "import.platform.linux.step5": "下のスクリプトをコピーしてターミナルに貼り付けます。",
        "import.platform.android.step1": "Shizuku と LogFox をインストールします。",
        "import.platform.android.step2": "ワイヤレスデバッグを有効化し、Shizuku とペアリングします。",
        "import.platform.android.step3": "Shizuku サービスを起動し、LogFox で Shizuku logger を選択します。",
        "import.platform.android.step4": "ゲームで履歴を開きながらログを記録します。",
        "import.platform.android.step5": "ログ内の \"token\" を見つけて値をコピーします。",
        "import.platform.ios.step1": "App Store から Stream をインストールします。",
        "import.platform.ios.step2": "iOS 設定で VPN プロファイル構成を許可します。",
        "import.platform.ios.step3": "Stream 証明書をインストールして信頼します（HTTPS 解析）。",
        "import.platform.ios.step4": "Endfield の通信履歴画面を開いたままにします。",
        "import.platform.ios.step5": "Stream でキャプチャを開始し、ゲーム内履歴を更新します。",
        "import.platform.ios.step6": "キャプチャを停止し、ef-webview.gryphline.com のリクエスト URL をコピーします。",
        "import.platform.soon_desc.android": "現在は PC のみ対応です。Android は近日対応予定です。",
        "import.platform.soon_desc.ios": "現在は PC のみ対応です。iOS は近日対応予定です。",
        "import.result.table.seq": "番号",
        "import.result.table.pool": "バナー",
        "import.result.table.rarity": "レア度",
        "import.result.table.name": "名前",
        "import.result.table.free": "無料",
        "import.result.table.new": "新規",
        "import.result.table.ts": "日時",
        "settings.cloud.yandex_unavailable": "Yandex Disk: 一時的に利用できません。",
        "common.ok": "OK",
    },
}

for language_code, mapping in EXTRA_TRANSLATIONS.items():
    TRANSLATIONS.setdefault(language_code, {}).update(mapping)

# Fill missing keys from English, then from Russian.
for language_code, mapping in TRANSLATIONS.items():
    if language_code in {"ru", "en"}:
        continue
    for key, value in TRANSLATIONS["en"].items():
        mapping.setdefault(key, value)
    for key, value in TRANSLATIONS["ru"].items():
        mapping.setdefault(key, value)


def normalize_language_code(value: str | None) -> str:
    """Normalize user-provided language value to one supported code."""
    raw = (value or "").strip().lower()
    if not raw:
        return DEFAULT_LANGUAGE

    raw = raw.replace("_", "-")
    if raw in SUPPORTED_LANGUAGES:
        return raw

    if raw.startswith("zh"):
        return "zh-hans"
    if raw.startswith("ja"):
        return "ja"
    if raw.startswith("de"):
        return "de"
    if raw.startswith("en"):
        return "en"
    if raw.startswith("ru"):
        return "ru"
    return DEFAULT_LANGUAGE


def _language_from_accept_header(header_value: str | None) -> str:
    """Pick first supported language from Accept-Language header."""
    header = (header_value or "").strip()
    if not header:
        return DEFAULT_LANGUAGE
    parts = [item.split(";")[0].strip() for item in header.split(",")]
    for part in parts:
        normalized = normalize_language_code(part)
        if normalized in SUPPORTED_LANGUAGES:
            return normalized
    return DEFAULT_LANGUAGE


def get_request_language(request) -> str:
    """Resolve active language from request cache/session/cookie/header."""
    if request is None:
        return DEFAULT_LANGUAGE

    cached = getattr(request, "site_language", None)
    if cached:
        return normalize_language_code(cached)

    session_lang = None
    if hasattr(request, "session"):
        session_lang = request.session.get(SITE_LANGUAGE_SESSION_KEY)
    cookie_lang = request.COOKIES.get(SITE_LANGUAGE_COOKIE_KEY)
    accepted_lang = _language_from_accept_header(request.META.get("HTTP_ACCEPT_LANGUAGE"))
    resolved = normalize_language_code(session_lang or cookie_lang or accepted_lang)
    setattr(request, "site_language", resolved)
    return resolved


def get_language_options() -> List[Dict[str, str]]:
    """Return available language options for UI switcher."""
    return LANGUAGE_OPTIONS


def translate(language: str, key: str, **kwargs) -> str:
    """Translate key with fallback chain and optional format arguments."""
    normalized = normalize_language_code(language)
    text = (
        TRANSLATIONS.get(normalized, {}).get(key)
        or TRANSLATIONS[DEFAULT_LANGUAGE].get(key)
        or key
    )
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text
